version: '3.8'  

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "4200:80"  
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Development 