version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to the Dockerfile for Blazor (UI)
    ports:
      - "4200:80"  # Expose the frontend on port 4200
    depends_on:
      - backend  # Frontend waits for backend to be ready
    networks:
      - app-network  # Optional: define a custom network for both containers

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to the Dockerfile for .NET API (backend)
    ports:
      - "8080:80"  # Expose the backend on port 8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development  # Set environment variable for .NET API
    networks:
      - app-network  # Optional: connect to the same network as frontend

networks:
  app-network:  # Optional: define a custom network for the app
    driver: bridge
